### ISSUE TITLE
Collection#insert doesn't honor errors

### ISSUE THREAD

**Issue by dvv** [marcello3d/node-mongolian#30] opened 2011-06-25 15:06 UTC
Define a unique key on a collection. Try to add two documents with identical properties. No error is fired

**Comment by marcello3d** [comment] 2011-06-25 16:57
What's the mongo shell behavior? Would you mind contributing a test case?

**Comment by marcello3d** [comment] 2011-06-25 19:32
this is a dupe of #15, I'll have a fix soon

**Closed as completed by marcello3d** 2011-06-25 19:32 UTC
