### ISSUE TITLE
ensureIndex throws error about key name

### ISSUE THREAD

**Issue by aikar** [marcello3d/node-mongolian#59] opened 2011-11-09 21:27 UTC
I issue collection.ensureIndex({"foo.bar": 1}, {background: 1}, function() {});

and mongolian throws an error "Error: key foo.bar must not contain '.'

This is a bug... Key names very much so can contain a dot... its the only way I know to do embedded doc keys!

going to have to go back to mongoskin until this is fixed :(

**Comment by marcello3d** [comment] 2011-11-10 00:00
Good catch! The problem is the generated key name doesn't strip out dots. Do you hit this on the mongo shell as well? Their code seems to have the same bug: http://api.mongodb.org/js/1.8.1/symbols/src/shell_collection.js.html (scroll down to _genIndexName)

**Comment by marcello3d** [comment] 2011-11-14 03:30
I actually can't reproduce this problem. What version of mongodb are you using?

**Comment by aikar** [comment] 2011-11-14 19:32
1.8.2

```
key foo.bar must not contain '.'
Error: key foo.bar must not contain '.'
    at Error (unknown source)
    at Function.checkKey (./node_modules/mongolian/node_modules/mongodb/lib/mongodb/bson/bson.js:1304:11)
    at Function.serializeWithBufferAndIndex (./node_modules/mongolian/node_modules/mongodb/lib/mongodb/bson/bson.js:278:16)
    at [object Object].toBinary (./node_modules/mongolian/node_modules/mongodb/lib/mongodb/commands/insert_command.js:98:55)
    at [object Object].send (./node_modules/mongolian/node_modules/mongodb/lib/mongodb/connection.js:376:32)
    at ./node_modules/mongolian/lib/server.js:254:20
    at ./node_modules/mongolian/lib/util.js:19:18
    at MongolianServer.cacher [as _connection] (./node_modules/mongolian/node_modules/taxman/taxman.js:8:25)
    at MongolianServer.sendCommand (./node_modules/mongolian/lib/server.js:248:10)
    at ./node_modules/mongolian/lib/server.js:148:17
```

**Comment by aikar** [comment] 2011-11-14 19:47
I use this function

```
function index(col, key, dir) {
    var keyobj = {};
    keyobj[key] = dir || 1;
    db.collection(col).ensureIndex(keyobj, {background:1 }, function(err) {
        if (err) {
            console.error(err)
        }
    });
}
```

It works fine under Mongoskin, but throws that error with Mongolian.

**Comment by marcello3d** [comment] 2011-12-31 23:48
This should be resolved with the new buffalo-based backend.

**Closed as completed** 2011-12-31 23:52 UTC
